import { ProjectData } from "./PolaroidCard";

/* 
  Central source of truth for all projects.
  Images are reused placeholders for now.
*/

export const PROJECTS: ProjectData[] = [
  {
    id: "ttt-othello",
    title: "TTT & Othello Player",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Simulation", "Real-Time"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "car-well",
    title: "Car-in-a-well Simulation",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Simulation"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-ot",
    title: "Virtual OT",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Immersive", "Real-Time"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "leo-highway",
    title: "Leo Highway Chase",
    rotation: "rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "warehouse",
    title: "Warehouse Simulation",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Simulation", "Immersive", "Real-Time"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "physics",
    title: "Physics Simulation",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Simulation", "Real-Time"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "halara",
    title: "Halara",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Cognitive"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "alfaleus",
    title: "Alfaleus Eye Test",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Cognitive"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "chess-promo",
    title: "Chess Engine Promo",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },

  /* Importance 2 */

  {
    id: "mocap-ingame",
    title: "MoCap In-Game",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic", "Immersive"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-production",
    title: "Virtual Production",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Simulation", "Immersive"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "webgl-game",
    title: "WebGL Game",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive", "Real-Time"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "brand-study",
    title: "Brand Study & Asset Creation",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Branding"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-ot-promo",
    title: "Virtual OT - Promo",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-ot-render",
    title: "Virtual OT - Render",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "transport",
    title: "Transport DigiTwin",
    rotation: "rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Simulation", "Cinematic", "Content"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "nolimits",
    title: "NoLimits Reels",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Content"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "halara-brand",
    title: "Halara Brand Study",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Branding"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "futuristic-skit",
    title: "Futuristic Skit",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic", "Content"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "bharatanatyam",
    title: "MoCap Bharatanatyam",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "photogrammetry",
    title: "Photogrammetry",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Simulation"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "popup-store",
    title: "PopUp Store",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Branding"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },

  /* Importance 3 */

  {
    id: "blackout",
    title: "Black-Out Game",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Immersive", "Cinematic"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "loading-loop",
    title: "Seamless Loading Screen Loop",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "phone-ad",
    title: "Phone Concept Ad",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "posters",
    title: "Posters",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Content", "Branding"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "bgc",
    title: "BGC Promo",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Cinematic"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "storefront",
    title: "Storefront Mockup",
    rotation: "rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Branding"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
];

/* Unique tags derived from dataset */
export const TAGS = [
  "Interactive",
  "Simulation",
  "Real-Time",
  "Immersive",
  "Cinematic",
  "Cognitive",
  "Branding",
  "Content",
];