import { ProjectData } from "./PolaroidCard";

/* 
  Central source of truth for all projects.
  Images are reused placeholders for now.
*/

export const NEED_TAGS = [
  "Intelligence", "Understand Something", "Interactive Experience", 
  "Explain an Idea", "Immersive Environment", "Productivity", 
  "Produce Visual Story", "Simulate Real World Systems", "Prototype Concept"
];

export const CONTEXT_TAGS = [
  "Education", "Product Prototype", "Research", "Training", 
  "Behavioral Analysis", "Storytelling", "Marketing", "UX Design"
];

export const PLATFORM_TAGS = [
  "Real-Time System", "Web-App", "Simulation", "3D Environment", 
  "XR (AR/VR)", "Video"
];

export const ALL_TAGS = [...NEED_TAGS, ...CONTEXT_TAGS, ...PLATFORM_TAGS];


export const PROJECTS: ProjectData[] = [
  {
    id: "ttt-othello",
    title: "TTT & Othello Player",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Intelligence", "Understand Something", "Interactive Experience", "Education", "Product Prototype", "Real-Time System", "Web-App"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "car-well",
    title: "Car-in-a-well Simulation",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Understand Something", "Explain an Idea", "Education", "Research", "Simulation", "3D Environment"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-ot",
    title: "Virtual OT",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Immersive Environment", "Interactive Experience", "Intelligence", "Productivity", "Research", "Training", "Behavioral Analysis", "Simulation", "XR (AR/VR)", "3D Environment"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "leo-highway",
    title: "Leo Highway Chase",
    rotation: "rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Immersive Environment", "Produce Visual Story", "Storytelling", "Marketing", "Video", "3D Environment"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "warehouse",
    title: "Warehouse Simulation",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Immersive Environment", "Simulate Real World Systems", "Prototype Concept", "Explain an Idea", "Productivity", "Product Prototype", "Marketing", "Story Telling", "Real-Time System", "Simulation", "3D Environment", "XR (AR/VR)"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "physics",
    title: "Physics Simulation",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Understand Something", "Explain an Idea", "Education", "Product Prototype", "Simulation", "3D Environment", "Real-Time System"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "halara",
    title: "Halara",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Immersive Environment", "Intelligence", "Understand Something", "Research", "Education", "Behavioral Analysis", "XR (AR/VR)", "3D Environment", "Web-App"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "alfaleus",
    title: "Alfaleus Eye Test",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Intelligence", "Understand Something", "Research", "Behavioral Analysis", "XR (AR/VR)", "Real-Time System"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "chess-promo",
    title: "Chess Engine Promo",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "Storytelling", "Marketing", "Video", "3D Environment"],
    importance: 1,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },

  /* Importance 2 */

  {
    id: "mocap-ingame",
    title: "MoCap In-Game",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Produce Visual Story", "Prototype Concept", "Storytelling", "Product Prototype", "Video", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-production",
    title: "Virtual Production",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Immersive Environment", "Produce Visual Story", "Prototype Concept", "Research", "Product Prototype", "Marketing", "Real-Time System", "XR (AR/VR)", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "webgl-game",
    title: "WebGL Game",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Prototype Concept", "Product Prototype", "UX Design", "Real-Time System", "Web-App"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "brand-study",
    title: "Brand Study & Asset Creation",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "UX Design", "Marketing"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-ot-promo",
    title: "Virtual OT - Promo",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "Marketing", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "virtual-ot-render",
    title: "Virtual OT - Render",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "Marketing", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "transport",
    title: "Transport DigiTwin",
    rotation: "rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "Product Prototype", "Marketing", "Storytelling", "Video", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "nolimits",
    title: "NoLimits Reels",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Produce Visual Story", "Marketing", "Storytelling", "Video"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "halara-brand",
    title: "Halara Brand Study",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "UX Design", "Marketing"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "futuristic-skit",
    title: "Futuristic Skit",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "Produce Visual Story", "Marketing", "Storytelling", "Video", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "bharatanatyam",
    title: "MoCap Bharatanatyam",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Simulate Real World Systems", "Produce Visual Story", "Marketing", "Storytelling", "Video", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "photogrammetry",
    title: "Photogrammetry",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Simulate Real World Systems", "Prototype Concept", "Research", "Product Prototype", "Simulation", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "popup-store",
    title: "PopUp Store",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Prototype Concept", "Immersive Environment", "Marketing", "3D Environment"],
    importance: 2,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },

  /* Importance 3 */

  {
    id: "blackout",
    title: "Black-Out Game",
    rotation: "-rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Interactive Experience", "Produce Visual Story", "Storytelling", "3D Environment", "Real-Time System"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "loading-loop",
    title: "Seamless Loading Screen Loop",
    rotation: "rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Produce Visual Story", "UX Design", "3D Environment", "Video"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "phone-ad",
    title: "Phone Concept Ad",
    rotation: "-rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Produce Visual Story", "Marketing", "Video", "3D Environment"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "posters",
    title: "Posters",
    rotation: "rotate-2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Explain an Idea", "UX Design"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "bgc",
    title: "BGC Promo",
    rotation: "-rotate-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Produce Visual Story", "Marketing"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "storefront",
    title: "Storefront Mockup",
    rotation: "rotate-3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non auctor tortor. Nam venenatis blandit nunc in ullamcorper. Etiam eget cursus mi, vitae egestas tellus.",
    link: "#",
    tags: ["Prototype Concept", "Immersive Environment", "Marketing"],
    importance: 3,
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=600&auto=format&fit=crop",
  },
];

/* Unique tags derived from dataset */
export const TAGS = [
  "Interactive",
  "Simulation",
  "Real-Time",
  "Immersive",
  "Cinematic",
  "Cognitive",
  "Branding",
  "Content",
];